In [4]:
import torch
x=torch.tensor([1,2,3,4,5])
y = torch.rand(5, 3)

print(x)
print(y)

tensor([1, 2, 3, 4, 5])
tensor([[0.0130, 0.6460, 0.8017],
        [0.9603, 0.0815, 0.9528],
        [0.0689, 0.2673, 0.7323],
        [0.2958, 0.4601, 0.3221],
        [0.9228, 0.8669, 0.0210]])


In [5]:

x = torch.tensor([1.0, 2.0, 3.0])
print('1D Tensor: \n', x)

y = torch.zeros((3, 3))
print('2D Tensor: \n', y)


a = torch.tensor([1.0, 2.0])
b = torch.tensor([3.0, 4.0])

print('Element Wise Addition of a & b: \n', a + b)

print('Matrix Multiplication of a & b: \n',
      torch.matmul(a.view(2, 1), b.view(1, 2)))

1D Tensor: 
 tensor([1., 2., 3.])
2D Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Element Wise Addition of a & b: 
 tensor([4., 6.])
Matrix Multiplication of a & b: 
 tensor([[3., 4.],
        [6., 8.]])


In [6]:
# Reshaping and Transposing Tensors
t = torch.tensor([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print("Reshaping")
print(t.reshape(6, 2))

print("\nResizing")
print(t.view(2, 6))

print("\nTransposing")
print(t.transpose(0, 1))

Reshaping
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

Resizing
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

Transposing
tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])


In [7]:
import numpy as np
arr=np.array([1,2,3])
n=torch.from_numpy(arr)
print(n)


tensor([1, 2, 3])


In [ ]:

#step 1
z =torch.tensor([1.,2.,3.])

#step 2
y = torch.tensor([2.,3.,4.])