Numpy Array Operations

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print("Basic slicing-\n",arr[2:4])
print("Slicing with step-\n",arr[1:5:2])
print("Slicing with negative step-\n",arr[4:0:-1])

Basic slicing-
 [3 4]
Slicing with step-
 [2 4]
Slicing with negative step-
 [5 4 3 2]


In [3]:
arr_2s=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specific element in 2D array-",arr_2s[1,2])
print("entire row in 2D array-",arr_2s[0,:])
print("Slicing 2D array-\n",arr_2s[0:2,1:3])
print("Slicing with step in 2D array-\n",arr_2s[0:3:2,0:3:2])

specific element in 2D array- 6
entire row in 2D array- [1 2 3]
Slicing 2D array-
 [[2 3]
 [5 6]]
Slicing with step in 2D array-
 [[1 3]
 [7 9]]


Sorting

In [5]:
unsorted_arr=np.array([3,1,4,2,5])
sorted_arr=np.sort(unsorted_arr)
print("unsorted array-",unsorted_arr)
print("sorted array-",sorted_arr)

arr_2d_unsorted=np.array([[3,1,4],[2,5,6],[9,7,8]])
sorted_arr_2d=np.sort(arr_2d_unsorted,axis=0)
print("unsorted 2D array-\n",arr_2d_unsorted)
print("sort 2d array by columns-\n",sorted_arr_2d)


unsorted array- [3 1 4 2 5]
sorted array- [1 2 3 4 5]
unsorted 2D array-
 [[3 1 4]
 [2 5 6]
 [9 7 8]]
sort 2d array by columns-
 [[2 1 4]
 [3 5 6]
 [9 7 8]]


Filter

In [ ]:
numbers=np.array([1,2,3,4,5])
even_numbers=numbers[numbers%2==0]
print("even numbers",even_numbers)

Filter with mask

In [ ]:
mask=numbers>3
print("numbers greater than 3",numbers[mask])

where_result=np.where(numbers>3)
print("where result",where_result)
print("where ",numbers[where_result])


condition_array=np.where(numbers>2,numbers*4,numbers) # condtion like ternary operator in javascript
print(condition_array)

numbers greater than 3 [4 5]
where result (array([3, 4]),)
where  [4 5]
[ 1  2 12 16 20]


Adding and removing data

In [3]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


##array compatibility

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9,10])

print("compatibility shapes",a.shape==b.shape)
print("compatibility shapes",a.shape==c.shape)

In [7]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])

with_new_row=np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print(with_new_col)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [8]:
arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,2)
print("array after deletion",deleted)

array after deletion [1 2 4 5]
