In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
sales_data=np.array([[1, 4134, 23925,  8657],
       [2, 4116, 23875,  9142],
       [3, 4673, 27197, 10645],
       [4, 4580, 25637, 10456],
       [5, 5109, 27995, 11299],
       [6, 5011, 27419, 10625],
    ])

print("sales analysis")
print("\n sales data shape",sales_data.shape)
print("sample data for first three rest-",sales_data[:3])

sales analysis

 sales data shape (6, 4)
sample data for first three rest- [[    1  4134 23925  8657]
 [    2  4116 23875  9142]
 [    3  4673 27197 10645]]


In [3]:
#total sales per year
print(np.sum(sales_data,axis=0))
yearly_total=np.sum(sales_data[:,1:],axis=0)
print(yearly_total)

#minimum sales per restaurant
min_sales=np.min(sales_data[:,1:],axis=1)
print(min_sales)

#maximum sales per year
max_sale= np.max(sales_data[:,1:],axis=0)
print(max_sale)

#average sales per restaurant
avg_sales=np.average(sales_data[:,1:],axis=1)
print(avg_sales)

[    21  27623 156048  60824]
[ 27623 156048  60824]
[4134 4116 4673 4580 5109 5011]
[ 5109 27995 11299]
[12238.66666667 12377.66666667 14171.66666667 13557.66666667
 14801.         14351.66666667]


In [ ]:
cumsum=np.cumsum(sales_data[:,1:],axis=0)
print(cumsum)

plt.figure(figsize=(10,6))
plt.plot(np.mean(cumsum,axis=0))
plt.title("Average cumulative sales for all restaurants")
plt.xlabel("years")
plt.ylabel("sales")
plt.grid(True)
plt.show()

In [8]:
vector1=np.array([1,2,3,4,5])
vector2=np.array([6,7,8,9,10])
print("vector addition:-",vector1+vector2)

print("dot product",np.dot(vector1,vector2))
angle=np.arccos(np.dot(vector1,vector2)/(np.linalg.norm(vector1)*np.linalg.norm(vector2)))
print(angle)

vector addition:- [ 7  9 11 13 15]
dot product 130
0.26554161733900966


In [ ]:
restaurant_types=np.array(['biryani','chinese','pizza','burger'])
vectorized_upper=np.vectorize(str.upper)
print("vectorized Upper",vectorized_upper(restaurant_types))

In [11]:
monthly_avg=sales_data[:,1:]/12
print(monthly_avg)

[[ 344.5        1993.75        721.41666667]
 [ 343.         1989.58333333  761.83333333]
 [ 389.41666667 2266.41666667  887.08333333]
 [ 381.66666667 2136.41666667  871.33333333]
 [ 425.75       2332.91666667  941.58333333]
 [ 417.58333333 2284.91666667  885.41666667]]
