In [6]:
import numpy as np

zeros=np.zeros((3,4))
print(zeros)

ones=np.ones((3,4))
print("ones array-\n",ones)

full=np.full((3,4),5)
print("full array-\n",full)


random=np.random.random((3,4))
print("random array-\n",random)

sequence=np.arange(0,10,2)
print("sequence array-\n",sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array-
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array-
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
random array-
 [[0.53019795 0.83872835 0.58154871 0.68243623]
 [0.35887866 0.77739117 0.67749816 0.77789214]
 [0.81607446 0.58331929 0.16777744 0.47826408]]
sequence array-
 [0 2 4 6 8]


In [7]:
vector=np.array([1,2,3,4])
print("vector array-\n",vector)


matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix array-\n",matrix)


tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("tensor array-\n",tensor)

vector array-
 [1 2 3 4]
matrix array-
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor array-
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [8]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2D array-\n",arr)
print("shape of array-",arr.shape)
print("number of dimensions-",arr.ndim)
print("size of array-",arr.size)
print("data type of array-",arr.dtype)

2D array-
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
shape of array- (2, 5)
number of dimensions- 2
size of array- 10
data type of array- int64


Array reshaping

In [ ]:
arr=np.arange(10)
print("original array-\n",arr)
reshaped_arr=arr.reshape(2,5)
print("reshaped array-\n",reshaped_arr)

flattened_arr=reshaped_arr.flatten()
print("flattened array-\n",flattened_arr)

# ravel (returns  view , instead of copy)
ravelled_arr=reshaped_arr.ravel()
print("ravelled array-\n",ravelled_arr)

# Transpose
transposed_arr=reshaped_arr.T
print("transposed array-\n",transposed_arr)
