In [7]:
import numpy as np
import matplotlib.pyplot as plt

## 1. Save & Load a Single Array — `.npy`

# Phase 4 — Saving & Loading NumPy Arrays

NumPy provides several ways to persist arrays to disk:
| Method | Format | Use case |
|---|---|---|
| `np.save` / `np.load` | `.npy` (binary) | Single array, fast |
| `np.savez` / `np.load` | `.npz` (compressed binary) | Multiple arrays together |
| `np.savetxt` / `np.loadtxt` | `.csv` / `.txt` (text) | Human-readable, shareable |

In [8]:
array1=np.array([1,2,3,4,5])
array2=np.random.rand(3,3)
array3=np.zeros((3,3))

In [9]:
np.save('array1.npy',array1)
np.save('array2.npy',array2)
np.save('array3.npy',array3)

In [10]:
loaded_array1=np.load('array1.npy')
print(loaded_array1)

[1 2 3 4 5]


In [11]:
# Loading a 3D array saved from a previous session
# 3DSpiral.npy contains x,y,z coordinates of a 3D spiral curve
load_picture = np.load('3DSpiral.npy')
print("Shape of 3D Spiral data:", load_picture.shape)
print("Data type:", load_picture.dtype)
print("First 3 points:\n", load_picture[:3])

Shape of 3D Spiral data: (100, 3)
Data type: float64
First 3 points:
 [[-0.40967154 -0.70918573  3.63626201]
 [ 0.26922384  1.20070167  0.15703993]
 [ 0.66161218  0.78332851  0.94112044]]


## 2. Save & Load Multiple Arrays — `.npz`

Use `np.savez` to bundle several arrays into one file. Load them back as a dictionary-like object.

In [ ]:
scores = np.array([85, 90, 78, 92, 88])
grades = np.array(['B', 'A', 'C', 'A', 'B'])

# Save multiple arrays into one .npz file
np.savez('student_data.npz', scores=scores, grades=grades)

# Load them back
loaded = np.load('student_data.npz', allow_pickle=True)
print("Keys in npz file:", list(loaded.keys()))
print("Scores:", loaded['scores'])
print("Grades:", loaded['grades'])

## 3. Save & Load as Text — `.csv` / `.txt`

`np.savetxt` writes human-readable files. Useful when sharing data with non-Python tools (Excel, R, etc.).

In [ ]:
data = np.array([[1, 85, 23925],
                 [2, 90, 27197],
                 [3, 78, 25637]])

# Save as CSV with header
np.savetxt('results.csv', data, delimiter=',', header='id,score,sales', comments='', fmt='%d')

# Load it back
loaded_csv = np.loadtxt('results.csv', delimiter=',', skiprows=1)
print("Loaded CSV data:\n", loaded_csv)
print("Data type:", loaded_csv.dtype)